describe('Smoke Go2Che', () => {
    it('header submenu is navigate user', () => {
        cy.viewport(1117, 800)
        cy.visit('/')
        cy.get('.burger-menu')
            .should('be.visible')
            .click()
    // Navigate to Worth seeing page via header
        cy.get('.menu-header-ua-container')
            .should('be.visible')
            .contains('Дозвілля')
            .should('be.visible')
            .click()
        cy.url().should('include', '/leisure/')
    // Navigate to Contacts page via header
        cy.get('.burger-menu')
            .should('be.visible')
            .click()
        cy.get('.menu-header-ua-container')
            .should('be.visible')
            .contains('Організація поїздки')
            .should('be.visible')
            .click()
        cy.url().should('include', 'organisation-trips/')
    })
})